application: naclforth
version: 1
runtime: python
api_version: 1

default_expiration: "1h"

handlers:

- url: /favicon.ico
  static_files: static/naclforth.ico
  upload: static/naclforth.ico

- url: /favicon.png
  static_files: static/naclforth.png
  upload: static/naclforth.png

- url: /naclforth.nmf
  static_files: static/naclforth.nmf
  upload: static/naclforth.nmf
  mime_type: application/octet-stream

- url: /naclforth_x86-32.nexe
  static_files: static/naclforth_x86-32.nexe
  upload: static/naclforth_x86-32.nexe
  mime_type: application/octet-stream

- url: /naclforth_x86-64.nexe
  static_files: static/naclforth_x86-64.nexe
  upload: static/naclforth_x86-64.nexe
  mime_type: application/octet-stream

- url: /.*
  script: naclforth.py
  secure: always
