application: naclforth
version: 1
runtime: python
api_version: 1

default_expiration: "1h"

handlers:

- url: /favicon.ico
  static_files: static/nacl4th.ico
  upload: static/nacl4th.ico

- url: /favicon.png
  static_files: static/nacl4th.png
  upload: static/nacl4th.png

- url: /forth_x86-32.nexe
  static_files: static/forth_x86-32.nexe
  upload: static/forth_x86-32.nexe
  mime_type: application/octet-stream
  expiration: "5s"

- url: /forth_x86-64.nexe
  static_files: static/forth_x86-64.nexe
  upload: static/forth_x86-64.nexe
  mime_type: application/octet-stream
  expiration: "5s"

- url: /forth.boot
  static_files: static/forth.boot
  upload: static/forth.boot
  mime_type: application/octet-stream
  expiration: "5s"

- url: /.*
  script: naclforth.py
  secure: always
