application: naclforth
version: 1
runtime: python
api_version: 1

default_expiration: "5s"

handlers:

- url: /(.*\.(ico|png))
  static_files: static/\1
  upload: static/(.*\.(ico|png))

- url: /(.*\.(nmf|nexe))
  static_files: static/\1
  upload: static/(.*\.(nmf|nexe))
  mime_type: application/octet-stream

- url: /.*
  script: naclforth.py